version: "3"
services:
  cubeapm:
    image: cubeapm/cubeapm:v1.11.0
    volumes:
      - ./data_volume/cubeapm:/root/data
      - ./config.properties:/root/config.properties
    environment:
      - CUBE_CONFIG_FILE=/root/config.properties
    ports:
      - 3125:3125

  fluent-bit:
    image: fluent/fluent-bit:3.2.2
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - 24224:24224
      - 24224:24224/udp

  log-gen:
    image: busybox:1.37.0
    command:
      [
        "sh",
        "-c",
        "while true; do echo -n `date -Iseconds`; echo -n ' INFO start '; for i in $(seq 1 8000); do echo -n 'mid '; done; echo end; echo new; sleep 5; done;",
      ]
    logging:
      driver: fluentd
      options:
        tag: sample
    depends_on:
      - fluent-bit
